spring.application.name=release-radar

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/release_radar
spring.datasource.username=release_radar
spring.datasource.password=release_radar
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
logging.level.org.springframework.security=DEBUG

jwt.secret=cmVsZWFzZS1yYWRhci1kZXYtc2VjcmV0LWtleS0zMmI=
jwt.expiration-ms=86400000
